import sss from "../assets/stakleni-sjaj-srebrna.jpg";
import ssg from "../assets/stakleni-sjaj-zlatna.jpg";
import lsb from "../assets/lux-set-bakarna.jpg";
import lss from "../assets/lux-set-srebrna.jpg";
import lsz from "../assets/lux-set-zlatna.jpg";

export const productsData = [
  {
    id: 1,
    name: "Činija za Žito",
    all: "svi",
    category: "slava",
    subcategory: "pojedinacno",
    image: [""],
    color: [],
    description:
      "U ponudi su više modela staklenih činija. U cenu proizvoda je uračunata i dekoracija koju radim po želji! Četvrtasti model je prečnika ___ cm u najširem delu, dok je okrugli model prečnika ___ cm u najširem delu. Poslužite svoje goste kako valja i dolikuje!",
    price: 1499,
  },
  {
    id: 2,
    name: "Postolje za kolač",
    all: "svi",
    category: "slava",
    subcategory: "pojedinacno",
    image: [""],
    color: [],
    description:
      "Stakleno postolje je prečnika  __cm. Ono može biti idealno za slavski kolač, kao i za sitne kolače koje servirate na slavskoj trpezi. U cenu proizvoda je uračunata i dekoracija koju radim po želji!",
    price: 2299,
  },
  {
    id: 3,
    name: "Postolje za slavsku sveću - veće",
    all: "svi",
    category: "slava",
    subcategory: "pojedinacno",
    image: [""],
    color: [],
    description:
      "Veće stakleno postolje je visine 14cm. U ponudi su i manje stakleno postolje visine 9 cm. U cenu proizvoda je uračunata i dekoracija koju radim po želji!",
    price: 1499,
  },
  {
    id: 4,
    name: "Postolje za slavsku sveću - manje",
    all: "svi",
    category: "slava",
    subcategory: "pojedinacno",
    image: [""],
    color: [],
    description:
      "Stakleno postolje visine 9 cm. U ponudi su i veće stakleno postolje visine 14cm. U cenu proizvoda je uračunata i dekoracija koju radim po želji!",
    price: 899,
  },
  {
    id: 5,
    name: "Rakijska flaša",
    all: "svi",
    category: "slava",
    subcategory: "pojedinacno",
    image: [""],
    color: [],
    description:
      "U ponudi su dva modela rakijskih flaša. Zapremina oba modela je 0,4L. U cenu proizvoda je uračunata i dekoracija koju radim po želji!",
    price: 1699,
  },

  {
    id: 6,
    name: "Rakijske čašice - 6 kom",
    all: "svi",
    category: "slava",
    subcategory: "pojedinacno",
    image: [""],
    color: [],
    description:
      "U ponudi su više modela čašica i čokanjčiće. U redovnom setu dolazi 6 kom, ali je moguća korekcija količine na upit. U cenu proizvoda je uračunata i dekoracija koju radim po želji! Pored klasičnih modela, u ponudi imam i lux model rakijskih čašica italijanskog brenda.",
    price: 2799,
  },
  {
    id: 7,
    name: "Rakijske čašice (LUX) - 6 kom",
    all: "svi",
    category: "slava",
    subcategory: "pojedinacno",
    image: [""],
    color: [],
    description:
      "Italijanske staklene čašice za rakiju vrhunskog kvaliteta i atraktivnog izgleda. U redovnom setu dolazi 6 kom, ali je moguća korekcija količine na upit. U cenu proizvoda je uračunata i dekoracija koju radim po želji!",
    sale: "lux",
    price: 3699,
  },
  {
    id: 8,
    name: "Vinske čaše - 6 kom",
    all: "svi",
    category: "slava",
    subcategory: "pojedinacno",
    image: [""],
    color: [],
    description:
      "Čaše za vino klasičnog izgleda i univerzalne namene. Moguća je korekcija količine čaša na upit. U cenu proizvoda je uračunata dekoracija koju radim po želji!",
    price: 3799,
  },
  {
    id: 9,
    name: "Vinske čaše (LUX) - 6 kom",
    all: "svi",
    category: "slava",
    subcategory: "pojedinacno",
    image: [""],
    color: [],
    description:
      "U ponudi su više modela čaša za crno i belo vino poznatih proizvođača, izrađenih od tankog stakla vrhunskog kvaliteta. Za detaljan pregled modela, budite slobodni da me kontaktirate. U redovnom setu dolazi 6 kom, ali je moguća korekcija količine na upit. U cenu proizvoda je uračunata i dekoracija koju radim po želji!",
    sale: "lux",
    price: 4999,
  },
  {
    id: 10,
    name: "Prstenovi za salvete - 6 kom",
    all: "svi",
    category: "slava",
    subcategory: "pojedinacno",
    image: [""],
    color: [],
    description:
      "U ponudi su dva modela prstenčića izrađenih od fine metalne legure. Svaki model je dostupan u tri nijanse: zlatna, srebrna i roze zlato. U regularnom setu dolazi 6 kom, ali je moguća korekcija količine na upit.",
    price: 1199,
  },
  {
    id: 11,
    name: "Viljuščice - 6 kom",
    all: "svi",
    category: "slava",
    subcategory: "pojedinacno",
    image: [""],
    color: [],
    description:
      "Viljuškice su dužine ___cm i izrađene su od nerđajuće metalne legure. Dostupne su u četiri nijanse: zlatna, srebrna, crna i roze zlato. U regularnom setu dolazi 6 kom, ali je moguća korekcija količine na upit.",
    price: 799,
  },
  {
    id: 12,
    name: "Kašičice",
    category: "slava",
    subcategory: "pojedinacno",
    image: [""],
    color: [],
    description:
      "Kašičice su dužine ___cm i izrađene su od nerđajuće metalne legure. Dostupne su u četiri nijanse: zlatna, srebrna, crna i roze zlato. U regularnom setu dolazi 6 kom, ali je moguća korekcija količine na upit.",
    price: 1299,
  },
  {
    id: 13,
    name: "STAKLENI SJAJ",
    category: "slava",
    subcategory: "set",
    image: [sss, ssg],
    color: ["silver", "gold"],
    description:
      "Set sadrži činiju za žito i vinsku čašu ili dve čaše za kašike. Imate mogućnost izbora modela činije i čaše za kašike. U cenu seta je uračunata dekoracija proizvoda koju radim po želji!",
    sale: "bestsellers",
    price: 2599,
  },
  {
    id: 14,
    name: "DOMAĆINSKI SET",
    category: "slava",
    subcategory: "set",
    image: [""],
    color: [],
    description:
      "Set sadrži rakijsku flašu i set od 6 rakijskih čašica. Imate mogućnost izbora modela rakijske flaše i čašica ili čokanjčića. U cenu seta je uračunata dekoracija proizvoda koju radim po želji!",
    price: 3499,
  },
  {
    id: 15,
    name: "SRPSKA TRADICIJA",
    category: "slava",
    subcategory: "set",
    image: [""],
    color: [],
    description:
      "Set sadrži činiju za žito, vinsku čašu ili dve čaše za kašike, postolje za slavski kolač i rakijsku flašu. Imate mogućnost izbora modela činije, čaše za kašike i rakijske flaše. U cenu seta je uračunata dekoracija proizvoda koju radim po želji!",
    price: 4999,
  },
  {
    id: 16,
    name: "LUX SLAVSKI SET",
    category: "slava",
    subcategory: "set",
    image: [lsb, lss, lsz],
    color: ["brown", "silver", "gold"],
    description:
      "Set sadrži činiju za žito, vinsku čašu, čašu za kašike, poslužavnik. Uz ovaj set dobijate 3 kašičice GRATIS u boji odabrane dekoracije. Imate mogućnost izbora modela činije i čaše za kašike. U cenu seta je uračunata dekoracija proizvoda koju radim po želji!",
    price: 5499,
  },
  {
    id: 17,
    name: "YING&YANG partneri",
    category: "svadba",
    subcategory: "set",
    image: [""],
    color: [],
    description:
      "Mladenačke čaše u crno-beloj ili teget-beloj kombinaciji sa inicijalima ili natpisima Mr i Mrs po želji, sa mašnama ili bez njih. Regularno dostupne boje inicijala i natpisa su: zlatna, srebrna i rose gold. Postoji mogućnost dostupnosti i drugih boja na upit. Moguće je dodati inicijale i datum na stopice čaša.",
    price: 3799,
  },
  {
    id: 18,
    name: "Gutljaj elegancije",
    all: "svi",
    category: "svadba",
    subcategory: "set",
    image: [""],
    color: [],
    description:
      "Čaša za njega je u dekoraciji crnog elegantnog smokinga, dok njena čaša oslikava belu venčanicu sa veom i ružicama. Moguće je dodati inicijale i datum na stopice čaša.",
    price: 3999,
  },
  {
    id: 19,
    name: "Anđeoska krila",
    all: "svi",
    category: "svadba",
    subcategory: "set",
    image: [""],
    color: [],
    description:
      "Najprodavaniji model u zlatnom i srebrnom izdanju sa mašnama ili bez njih. Ovaj model je moguće izraditi i u drugim bojama na upit. Inicijali i natpisi Mr i Mrs regularno su dostupni u sledećim bojama: zlatna, srebrna i rose gold. Postoji mogućnost dostupnosti i drugih boja na upit. Moguće je dodati inicijale i datum na stopice čaša.",
    sale: "bestsellers",
    price: 3499,
  },
  {
    id: 20,
    name: "Ružin vrat",
    all: "svi",
    category: "svadba",
    subcategory: "set",
    image: [""],
    color: [],
    description:
      "Ovaj model sadrži ruže sa inicijalima ili natpisima, sa ili bez mašnica. Regularno su dostupne ruže u sledećim bojama: bela, žuta, crvena i plava. Postoji mogućnost dostupnosti i drugih boja na upit. Moguće je dodati inicijale i datum na stopice čaša.",
    price: 3499,
  },
  {
    id: 21,
    name: "Čarolija prirode",
    all: "svi",
    category: "svadba",
    subcategory: "set",
    image: [""],
    color: [],
    description:
      "Stopica i drška čaša od tankog kanapa uz veštačko cveće po želji. Moguće je dodati inicijale i natpise Mr i Mrs, kao i datum na stopice čaša.",
    price: 4299,
  },
  {
    id: 22,
    name: "Biserni sjaj",
    all: "svi",
    category: "svadba",
    subcategory: "set",
    image: [""],
    color: [],
    description:
      "Čaše za mladence sa belim biserima različitih veličina. Moguće je dodati natpise po želji sa suprotne strane, kao i inicijale i datum na stopice čaše.",
    price: 4499,
  },
  {
    id: 23,
    name: "Kraljevska magija",
    all: "svi",
    category: "svadba",
    subcategory: "set",
    image: [""],
    color: [],
    description:
      "Čaše za mladence u specijalnom izdanju! Ovaj model je moguće izraditi u sledećim nijansama: zlatna, srebrna, crna, teget i bela.",
    sale: "lux",
    price: 4999,
  },
  {
    id: 24,
    name: "Kristalna kap",
    all: "svi",
    category: "svadba",
    subcategory: "set",
    image: [""],
    color: [],
    description:
      "Čaše za mladence u specijalnom izdanju! Ovaj model je moguće izraditi u zlatnoj i srebrnoj varijanti. Moguće je dodati inicijale ili natpise Mr i Mrs, kao i datum na stopice čaša.",
    sale: "lux",
    price: 5599,
  },
  {
    id: 25,
    name: "Crkveni pehar",
    all: "svi",
    category: "svadba",
    subcategory: "pojedinacno",
    image: [""],
    color: [],
    description:
      "Crkveni pehar u specijalnom izdanju! Ovaj model je moguće izraditi u srebrnoj i zlatnoj varijanti. Datum, inicijali i natpisi se dodaju po želji.",
    sale: "lux",
    price: 2999,
  },
  {
    id: 26,
    name: "Čaše za bračne svedoke",
    all: "svi",
    category: "svadba",
    subcategory: "set",
    image: [""],
    color: [],
    description:
      "Čaše za bračne svedoke u željenim bojama sa inicijalima ili kumskim natpisima, sa mašnama ili bez njih. Moguće je dodati inicijale i datum na stopice čaša.",
    price: 2499,
  },
  {
    id: 27,
    name: "Čaše za kumove - 4 kom",
    all: "svi",
    category: "svadba",
    subcategory: "set",
    image: [""],
    color: [],
    description:
      "Čaše za kumove u željenim bojama sa inicijalima ili kumskim natpisima, sa mašnama ili bez njih. Moguće je dodati inicijale i datum na stopice čaša. Veće količine kumskih čaša neophodno je naglasiti u upitu, čemu sledi formiranje posebne ponude.",
    price: 3999,
  },
  {
    id: 28,
    name: "Poklon za najbliže goste - 6 kom",
    all: "svi",
    category: "svadba",
    subcategory: "set",
    image: [""],
    color: [],
    description:
      "Stakleni čokanjčići za najbliže goste ukrašeni po želji. Moguće je odraditi personalizaciju, inicijale mladenaca i datum venčanja. Za poručivanje količine čokanjčića van ove ponude poslati upit.",
    price: 1999,
  },
  {
    id: 29,
    name: "Mladenačka čarolija",
    all: "svi",
    category: "svadba",
    subcategory: "set",
    image: [""],
    color: [],
    description:
      "Dve mladenačke čaše i crkveni pehar ukrašeni po želji. Moguće je dodati inicijale, natpise i datum venčanja. Napomena: ova ponuda se odnosi na modele mladenačkih čaša ispod 3.899 din.",
    sale: "specijalna",
    price: 4799,
  },
  {
    id: 30,
    name: "Bračna zdravica - 4 kom",
    all: "svi",
    category: "svadba",
    subcategory: "set",
    image: [""],
    color: [],
    description:
      "Čaše za mladence i bračne partnere po specijalnoj ceni! Za mladenačke čaše je moguće odabrati jedan od sledećih modela: Ying&Yang partneri, Anđeoska krila ili Ružin vrt. Čaše za bračne partnere su ukrašene u kompletu, u željenim bojama, sa inicijalima ili kumskim natpisima, sa mašnama ili bez njih. Moguće je dodati inicijale i datum na stopice čaša.",
    sale: "specijalna",
    price: 4999,
  },
];
